<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-KGDMBK1V" failures="0" tests="4" name="com.testng.parametesrsdemo.InvocationTimeOutDemo" time="4.113" errors="2" timestamp="18 Oct 2021 17:08:56 GMT" skipped="0">
  <testcase classname="com.testng.parametesrsdemo.InvocationTimeOutDemo" name="m4" time="3.022">
    <error message="Method com.testng.parametesrsdemo.InvocationTimeOutDemo.m4() didn&#039;t finish within the time-out 3000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.parametesrsdemo.InvocationTimeOutDemo.m4() didn't finish within the time-out 3000
at java.base@15.0.2/java.lang.Throwable.<init>(Throwable.java:318)
at java.base@15.0.2/java.lang.Exception.<init>(Exception.java:103)
at java.base@15.0.2/java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:90)
at java.base@15.0.2/java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:74)
at java.base@15.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@15.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base@15.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@15.0.2/java.lang.reflect.Method.invoke(Method.java:564)
at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:40)
at java.base@15.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base@15.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@15.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base@15.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base@15.0.2/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- m4 -->
  <testcase classname="com.testng.parametesrsdemo.InvocationTimeOutDemo" name="m1" time="0.029"/>
  <testcase classname="com.testng.parametesrsdemo.InvocationTimeOutDemo" name="m2" time="0.003"/>
  <testcase classname="com.testng.parametesrsdemo.InvocationTimeOutDemo" name="m3" time="1.059">
    <error message="Method com.testng.parametesrsdemo.InvocationTimeOutDemo.m3() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.parametesrsdemo.InvocationTimeOutDemo.m3() didn't finish within the time-out 1000
]]>
    </error>
  </testcase> <!-- m3 -->
</testsuite> <!-- com.testng.parametesrsdemo.InvocationTimeOutDemo -->
